{{- if .Values.externalIngress.enabled  }}
#
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: redirect-to-https
spec:
  {{- if  .Values.externalIngress.sslPolicy }}
  sslPolicy: {{ .Values.externalIngress.sslPolicy }}
  {{- end }}
  redirectToHttps:
    enabled: true
    responseCodeName: TEMPORARY_REDIRECT
{{- end }}