{{- if and .Values.deviceRegistryExample.enabled ( eq .Values.deviceRegistryExample.type "jdbc" ) ( eq .Values.deviceRegistryExample.jdbcBasedDeviceRegistry.horizontalPodAutoscaler.enabled true ) }}
#
# Copyright (c) 2019, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: device-registry-hpa
  namespace: {{ .Release.Namespace }}
spec:
  minReplicas: {{ .Values.deviceRegistryExample.jdbcBasedDeviceRegistry.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.deviceRegistryExample.jdbcBasedDeviceRegistry.horizontalPodAutoscaler.maxReplicas }}
  metrics: {{ toYaml .Values.deviceRegistryExample.jdbcBasedDeviceRegistry.horizontalPodAutoscaler.metrics | nindent 4 }}
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ .Release.Name }}-service-device-registry
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - periodSeconds: 120
          type: Pods
          value: 1
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - periodSeconds: 300
          type: Pods
          value: 1
{{- end }}