{{- if .Values.deviceCommunication.enabled }}
#
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "service-device-communication" "name" "service-device-communication" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  annotations:
    cloud.google.com/app-protocols: '{"http": "HTTP"}'
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}

{{- end }}